name: main

on:
  workflow_dispatch:
  #push:
  #  branches: [ main ]
  #  paths-ignore: 
  #    - 'README.md'
  #    - 'imgs/**'
  schedule:
    - cron: 0 7,15 * * *
  watch:
    types: [started]

jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
      - name: Install requirements
        run: |
          pip3 install -r ./requirements.txt
      - name: Run checkin
        run: |
          python3 ./main.py
        env:
          PUSHPLUS_TOKEN: '${{ secrets.PUSHPLUS_TOKEN }}'
          GLADOS_COOKIE: '${{ secrets.GLADOS_COOKIE }}'
          JUEJIN_COOKIE: '${{ secrets.JUEJIN_COOKIE }}'
      - uses: gautamkrishnar/keepalive-workflow@master  
